lang: zh-CN
title: CMS
author:
  name: FireLoong
  email: fireloong@foxmail.com
description: >-
  Write an awesome description for your new site here.

timezone: Asia/Shanghai
markdown: kramdown
# baseurl: /cms
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin